### ISSUE TITLE
How to get account nonce and sequence througn HTTP request?

### ISSUE THREAD

**Issue by Wangmmx** [okex/okexchain-javascript-sdk#38]
Hello, I found that many interfaces cannot be called normally. There are few questions that I want to know

1.In the HTTP document given https://documenter.getpostman.com, there is no interface for obtaining nonce and sequence, but this field is required to construct the transaction body and signature.

2.The method /okexchain/v1/auth/accounts obtained through the http client in the SDK also reported an error. What is the correct URL? What is the http node url of the main network? What about the testnet? 

3.The data in many documents is not uniform, chainId for testnet is okexchainevm-81  or okexchaintestnet-1 ? And is https:/13.230.73.12:8545 the testnet url?

4.The transaction body In HTTP document is not contains accountNumber and sequence, but in the source code it has, so what is the certain transaction body is？

Looking forward to your reply, both English and Chinese is fine, thanks again

**Comment by zccst** [comment]
1. already add new api：https://documenter.getpostman.com/view/13902793/TVsxAm58#8459a772-7adc-421f-9ff2-ebf71ae414fc, thanks for your suggest.
2. the mainnet full url is: https://www.okex.com/okexchain/v1/auth/accounts/yourAddress. you can get account_number and sequence. the testnet full url is: https://www.okex.com/okexchain-test/v1/auth/accounts/yourAddress.
3. okexchain mainnet chain-id is okexchain-66 and testnet chain-id is okexchain-65。other is local chain-id and url (you start okexchain node in you local environment, default is http://localhost:8545), you can modify it.
4. the certain transaction body is contains account_number and sequence, you can use jssdk construct it. thank you

**Comment by Wangmmx** [comment]
Thanks for all your responses! Thank you so much, I will try it now

**Comment by Wangmmx** [comment]
The problems mentioned yesterday have been solved. I successfully assembled the transaction body and broadcasted it, but the broadcast was unsuccessful, and an error was reported:
`{ StatusCodeError: 400 - {"error":"unrecognized concrete type name okexchain/token//MsgTransfer"}`

I think it is a problem with the transaction body,  my transaction body is built refer to the document Assembled, the type is also according to the `okexchain/token/MsgTransfer` written in the document. Why is this error reported? 
```
{
    "tx":{
        "msg":[
            {
                "type":"okexchain/token//MsgTransfer",
                "value":{
                    "amount":[
                        {
                            "amount":"100.000000000000000000",
                            "denom":"okt"
                        }
                    ],
                    "from_address":"okexchain1c59l52a8a73fsfwa8gr3xnru7272xq389wt2e4",
                    "to_address":"okexchain1a96g4msww75m5cmpz93uarj9xyf07kvkjyaman"
                }
            }
        ],
        "signatures":[
            {
                "pub_key":{
                    "type":"ethermint/PubKeyEthSecp256k1",
                    "value":"A1ons1ZMaggze6B/gSBVHVch6a6Ii81g33Bd51CdK8c9"
                },
                "signature":"********"
            }
        ],
        "memo":"",
        "fee":{
            "amount":[
                {
                    "amount":"10.000000000000000000",
                    "denom":"okt"
                }
            ],
            "gas":"200000"
        }
    },
    "mode":"block"
}
```

Also I want to ask, address generated by the testnet and mainnet are the same, right? And has the mainnet started to transfer OKT now?  I want to test but have no OKTs, where can I get OKT or testnet OKT?

**Comment by Wangmmx** [comment]
The problems mentioned yesterday have been solved. I successfully assembled the transaction body and broadcasted it, but the broadcast was unsuccessful, and an error was reported:
```
"error": {
        "status": 5004,
        "error": "SendTxError",
        "params": "{\"height\":\"0\",\"txhash\":\"A3B08FADD7A9B6ABB92690A68F35D994CFE9448448B2C6FECC5ED9C5C0BA2B75\",\"code\":9,\"raw_log\":\"unknown address: account okexchain1uv8k3j0nwgsglfvnmxlzc7taewsnrku58dfq3h does not exist\"}",
        "msg": "发送交易失败! {\"height\":\"0\",\"txhash\":\"A3B08FADD7A9B6ABB92690A68F35D994CFE9448448B2C6FECC5ED9C5C0BA2B75\",\"code\":9,\"raw_log\":\"unknown address: account okexchain1uv8k3j0nwgsglfvnmxlzc7taewsnrku58dfq3h does not exist\"}"
    }
```

Has the mainnet started to transfer OKT now?  I want to test but have no OKTs, where can I get OKT or testnet OKT?

And also I want to ask, address generated by the testnet and mainnet are the same, right?
Looking forward to your reply!

**Comment by Wangmmx** [comment]
The error: account okexchain1uv8k3j0nwgsglfvnmxlzc7taewsnrku58dfq3h does not exist, It means account does not have any OKTs, I got it.

@zccst 
1.Can I get OKT from Okex trade now? Has the mainnet started to transfer OKT? I saw several transfer txs.
2.Address generated by the testnet and mainnet are the same, right?
3.Is there any interface to encode the tx? I want to calculate txHash before the transaction sent, but it needed to encoded, I don't find the interface or sdk function.
4.Is the fee is fixed? How much does it cost ? 

Sorry to bother you again, hope you can reply me, thanks

**Comment by Wangmmx** [comment]
Closing
